service: morning-cd-glitch

provider:
  name: aws

plugins:
  - serverless-finch

custom:
  client:
    bucketName: 8bit.morningcd.com
    distributionFolder: build
    errorDocument: index.html
    objectHeaders:
      index.html:
        - name: Cache-Control
          value: no-cache
      service-worker.js:
        - name: Cache-Control
          value: no-cache
